/*
 * Even Fibonacci numbers
 * 
 * Problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *                          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Expected result: 4613732
 */
public class Euler2 {
    
    public static void main(String[] args){
        
        /** Determina valores iniciais para os primeiros dois fibonacci */
        long firstFibo = 0;       
        long secondFibo = 1;
        long nextFibo = firstFibo + secondFibo;
        long sum = 0;

        /** Enquanto o valor do termo nextFibo for menor que 4 milhões, verifica se o termoo é part e incrementa a soma */
        while (nextFibo <= 4000000){
            if (nextFibo % 2 == 0){
                sum += nextFibo;
            }

            /** Atualiza as variáveis para os valores seguintes */
            firstFibo = secondFibo; 
            secondFibo = nextFibo;
            nextFibo = firstFibo + secondFibo;
        }
        System.out.println(sum);
    }
}
